service: nail-salon-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    NODE_ENV: production
    DATABASE_URL: ${process.env.DATABASE_URL}
    FRONTEND_URL: ${process.env.FRONTEND_URL}
  vpc:
    securityGroupIds:
      - sg-05c0e25d952963997
    subnetIds:
      - subnet-00afb268a92fa99f9
      - subnet-0775c97c971619ea7
      - subnet-0d7b097279d901a74

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

plugins:
  - serverless-plugin-tracing

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.env"
